
name: Test Workflow Trigger

on:
  repository_dispatch:
    types: [json-change-detected]  # Custom event type to trigger the workflow

jobs:
  test-trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Echo Triggered Event
        run: echo "Workflow triggered by repository_dispatch event."

      - name: Log Commit Hash
        if: github.event_name == 'repository_dispatch'
        run: echo "Commit Hash: ${{ github.event.client_payload.commit_hash }}"
